/**
 * Static call metadata for the two phone scenes.
 *
 * The runtime manifests (`public/audio/<call>/manifest.json`, generated by
 * tooling/demo/generate-voices.ts) carry per-line *timing* + short captions +
 * the outcome, but NOT the full spoken dialogue. The full transcript lives only
 * in the tooling scripts, so we mirror it here (keyed by line id) and merge it
 * with the fetched manifest at play time - see useCallPlayer. That gives us a
 * real, DOM-rendered transcript (an a11y requirement) without shipping the whole
 * generator script to the client.
 */
export type CallId = 'airport-call' | 'hotel-call'
export type Speaker = 'agent' | 'callee'

export interface CallMeta {
  id: CallId
  /** Short scene label, e.g. "Appel - aéroport". */
  label: string
  /** Human title for the transcript heading. */
  title: string
  callee: {
    name: string
    short: string
    /** Public path (relative to base) of the callee's portrait. */
    face: string
  }
  agent: {
    name: string
    short: string
    face: string
  }
  /** line id → full spoken sentence (French). Fallback only: newer manifests
      embed the spoken text per line. Keyed to the *committed* audio manifests -
      after regenerating voices from the (now shorter) tooling scripts, drop or
      re-key these. */
  transcript: Record<number, string>
  /** line id → short fact that gets "stamped" on screen once that line has been
      spoken. The impactful skeleton of the call, instead of a full transcript.
      Also keyed to the committed manifests - re-key after a voice regen. */
  milestones: Record<number, string>
  /** Mirror of the manifest outcome - lets the notification/outro scenes render
      without spinning up a player or a second fetch. */
  outcome: {
    reference: string
    summary: string
    kind: 'airport' | 'hotel'
    notification: { title: string; body: string }
  }
}

export const CALLS: Record<CallId, CallMeta> = {
  'airport-call': {
    id: 'airport-call',
    label: 'Appel - aéroport',
    title: 'TripAssist IA → Assistance PMR, Paris-CDG',
    agent: { name: 'Assistant TripAssist', short: 'IA', face: 'faces/ai-agent.png' },
    callee: {
      name: 'Assistance PMR - Paris-CDG',
      short: 'CDG',
      face: 'faces/airport-agent.png',
    },
    transcript: {
      1: 'Assistance passagers à mobilité réduite de Paris-Charles-de-Gaulle, bonjour.',
      2: "Bonjour, je suis l'assistant TripAssist et j'appelle au nom de Madame Camille Moreau pour organiser son assistance embarquement. Elle voyage sur le vol Air France 7612 vers Cannes-Mandelieu, le 12 septembre au départ de dix heures cinq.",
      3: "Très bien, je note le vol AF 7612 du 12 septembre. Quel est le type d'assistance requis ?",
      4: "Madame Moreau se déplace en fauteuil roulant électrique et ne peut pas effectuer de transfert sans aide. Nous demandons une assistance de catégorie WCHC : prise en charge dès la dépose-minute, passage sécurité prioritaire, et embarquement assisté avec transfert jusqu'au siège.",
      5: "Entendu. Pour le fauteuil, s'agit-il d'une batterie sèche ou d'une batterie au lithium ? Nous devons le déclarer au commandant de bord.",
      6: "C'est un Permobil M3, cent quarante kilos, équipé d'une batterie Lithium-ion conforme à la réglementation IATA. Nous demandons qu'il voyage en soute et soit restitué en passerelle à l'arrivée à Cannes-Mandelieu, pas au tapis bagages.",
      7: "C'est parfaitement gérable. Je réserve l'assistance WCHC complète, avec restitution du fauteuil en passerelle à Cannes-Mandelieu. Je vous donne la référence : whisky-charlie-hôtel neuf-quatre-deux-sept.",
      8: 'Je confirme la référence WCH-9427. Une dernière chose : pouvez-vous prévoir la prise en charge quarante-cinq minutes avant l’embarquement, à la dépose-minute du Terminal 2F ?',
      9: "C'est noté : prise en charge à la dépose-minute du Terminal 2F, quarante-cinq minutes avant l'embarquement. Tout est confirmé pour Madame Moreau.",
      10: "Parfait, je vous remercie. J'enregistre la confirmation au registre de voyage de Madame Moreau. Excellente journée.",
    },
    milestones: {
      4: 'Assistance WCHC demandée',
      6: 'Batterie lithium déclarée',
      7: 'Réf. WCH-9427',
      9: 'Prise en charge T2F −45 min',
    },
    outcome: {
      reference: 'WCH-9427',
      kind: 'airport',
      summary:
        'Assistance WCHC à CDG · prise en charge T2F −45 min · fauteuil restitué en passerelle.',
      notification: {
        title: 'Aéroport confirmé',
        body: 'Réf. WCH-9427 · prise en charge Terminal 2F, 45 min avant le vol.',
      },
    },
  },
  'hotel-call': {
    id: 'hotel-call',
    label: 'Appel - hôtel',
    title: 'TripAssist IA → Réception, Hôtel le Mistral (Cannes)',
    agent: { name: 'Assistant TripAssist', short: 'IA', face: 'faces/ai-agent.png' },
    callee: {
      name: 'Réception - Hôtel le Mistral',
      short: 'Hôtel',
      face: 'faces/hotel-receptionist.png',
    },
    transcript: {
      1: 'Hôtel le Mistral, bonjour, que puis-je faire pour vous ?',
      2: "Bonjour, ici l'assistant TripAssist, j'appelle pour la réservation de Madame Camille Moreau, du 12 au 15 septembre, chambre 104. Je souhaite confirmer un point d'accessibilité essentiel avant son arrivée.",
      3: 'Bien sûr, je vois la réservation de Madame Moreau, trois nuits en chambre 104. De quel point s’agit-il ?',
      4: "Madame Moreau se déplace en fauteuil roulant. Elle a besoin d'une douche à l'italienne, de plain-pied, sans rebord ni marche - surtout pas d'une baignoire. Pouvez-vous me confirmer que la chambre 104 en dispose bien ?",
      5: 'Alors, laissez-moi vérifier… La chambre 104 est notre chambre PMR, mais je vois qu’elle est équipée d’une baignoire à porte, pas d’une douche de plain-pied.',
      6: "Ce ne sera pas adapté : Madame Moreau ne peut pas franchir de rebord. Disposez-vous d'une autre chambre accessible avec une véritable douche à l'italienne et un siège de douche rabattable ?",
      7: 'Laissez-moi regarder… Oui, la chambre 210 est une chambre accessible avec douche à l’italienne de plain-pied, barres d’appui et siège de douche rabattable. Je peux la réattribuer à Madame Moreau sans supplément.',
      8: "C'est parfait. Merci de basculer la réservation sur la chambre 210. Pouvez-vous aussi garantir un accès sans marche depuis l'entrée de l'hôtel jusqu'à la chambre, et un lit à hauteur de transfert ?",
      9: 'Oui, l’accès se fait par ascenseur, sans aucune marche, et le lit est à hauteur standard de transfert. Je bascule Madame Moreau sur la chambre 210. La nouvelle référence est bravo-roméo neuf-neuf-zéro-un.',
      10: "Je confirme, référence BR-9901, chambre 210 avec douche à l'italienne. J'enregistre la confirmation au registre de Madame Moreau. Merci beaucoup, bonne journée.",
    },
    milestones: {
      5: 'Chambre 104 : baignoire ✗',
      7: 'Chambre 210 : douche à l’italienne',
      9: 'Accès sans marche',
      10: 'Réf. BR-9901',
    },
    outcome: {
      reference: 'BR-9901',
      kind: 'hotel',
      summary: 'Chambre 210 · douche à l’italienne · accès sans marche · sans supplément.',
      notification: {
        title: 'Hôtel confirmé',
        body: 'Chambre 210, douche de plain-pied (réf. BR-9901). Sans supplément.',
      },
    },
  },
}
